name: Math Utility Project (CI included) | © 2025 by Hgnv11

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # 🧪 RUNNING TESTS FROM BOTH XML FILES
    - name: Run testng-parallel.xml
      run: mvn test -DsuiteXmlFile=testng-parallel.xml

    - name: Run testng-verbose.xml
      run: mvn test -DsuiteXmlFile=testng-verbose.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Distribute jar-war file
      run: mkdir staging && cp target/*.jar staging

    - name: Make hyperlink to jar-war file
      uses: actions/upload-artifact@v4
      with:
        name: cham_de_lay_jar
        path: staging
